[versions]
current = "0.1.0"
benmanes-versions = "0.50.0"
kotlin = "1.9.21"
jvm = "17"
detekt = "1.23.4"
dokka = "1.9.10"
kotlin-datetime = "0.5.0"
npm-joda-time = "2.18.2"
kover = "0.7.5"
binary-compatibility-validator = "0.13.2"
nexus = "1.3.0"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-library = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
benmanes-versions = { id = "com.github.ben-manes.versions", version.ref = "benmanes-versions" }
binarycompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator"}
nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }